import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import {Theme } from '@radix-ui/themes'
import "./globals.css";
import Navigation from '@/components/Navigation'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ReactNode } from "react";
import { ThemeProvider } from "next-themes";

export default function RootLayout({
      children,
    }: { children: ReactNode }) {
  return (
    <html lang="es" className="dark" suppressHydrationWarning>
      <body

      >
        <ThemeProvider   attribute="class">
        <Theme>
          <Navigation />
          <main>
            {children}
          </main>
        </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}

